//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poultry_farm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breeds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Breeds()
        {
            this.Chickens = new HashSet<Chickens>();
        }
    
        public int Id { get; set; }
        public string BreedName { get; set; }
        public int AverageEggsNumber { get; set; }
        public double AverageWeight { get; set; }
        public int IdDietNumber { get; set; }
    
        public virtual Diets Diets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chickens> Chickens { get; set; }
    }
}
