//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poultry_farm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cages
    {
        public int Id { get; set; }
        public int IdWorkshop { get; set; }
        public int IdChicken { get; set; }
        public int IdWorker { get; set; }
        public int RowNumber { get; set; }
        public int CageNumber { get; set; }
    
        public virtual Chickens Chickens { get; set; }
        public virtual Workers Workers { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
