//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poultry_farm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoultryFarmEntities : DbContext
    {
        public PoultryFarmEntities()
            : base("name=PoultryFarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breeds> Breeds { get; set; }
        public virtual DbSet<Cages> Cages { get; set; }
        public virtual DbSet<Chickens> Chickens { get; set; }
        public virtual DbSet<Diets> Diets { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
    }
}
